name: s390x-periodic

on:
  schedule:
    # We have several schedules so jobs can check github.event.schedule to activate only for a fraction of the runs.
    # Also run less frequently on weekends.
    - cron: 29 8 * * *  # about 1:29am PDT, for mem leak check and rerun disabled tests
  push:
    tags:
      - ciflow/periodic/*
    branches:
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ github.event.schedule }}
  cancel-in-progress: true

permissions: read-all

jobs:
  llm-td:
    name: before-test
    uses: ./.github/workflows/llm_td_retrieval.yml
    permissions:
      id-token: write
      contents: read

  target-determination:
    name: before-test
    uses: ./.github/workflows/target_determination.yml
    needs: llm-td
    permissions:
      id-token: write
      contents: read

  linux-ubuntu-24_04-py3-cpu-s390x-build:
    name: linux-ubuntu-24_04-py3-cpu-s390x
    uses: ./.github/workflows/_linux-build-s390x.yml
    with:
      build-environment: linux-s390x-binary-manywheel
      docker-image-name: pytorch/manylinuxs390x-builder:cpu-s390x-main
      runner: linux.s390x
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 5, runner: "linux.s390x" },
          { config: "default", shard: 2, num_shards: 5, runner: "linux.s390x" },
          { config: "default", shard: 3, num_shards: 5, runner: "linux.s390x" },
          { config: "default", shard: 4, num_shards: 5, runner: "linux.s390x" },
          { config: "default", shard: 5, num_shards: 5, runner: "linux.s390x" },
        ]}

  linux-ubuntu-24_04-py3-cpu-s390x-test:
    permissions:
      id-token: write
      contents: read
    name: linux-ubuntu-24_04-py3-cpu-s390x
    uses: ./.github/workflows/_linux-test-s390x.yml
    needs:
      - linux-ubuntu-24_04-py3-cpu-s390x-build
      - target-determination
    with:
      build-environment: linux-s390x-binary-manywheel
      docker-image: pytorch/manylinuxs390x-builder:cpu-s390x-main
      test-matrix: ${{ needs.linux-ubuntu-24_04-py3-cpu-s390x-build.outputs.test-matrix }}
      use-gha: true
